// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * UserSchema
 */
export type UserSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Google Id
     */
    google_id: string;
    /**
     * Picture
     */
    picture?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type AuthLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/callback';
};

export type AuthCallbackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthLogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthGetMeResponses = {
    /**
     * Successful Response
     */
    200: UserSchema;
};

export type AuthGetMeResponse = AuthGetMeResponses[keyof AuthGetMeResponses];

export type ChatAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/chats';
};

export type ChatAllResponses = {
    /**
     * Response Chat All
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ChatAllResponse = ChatAllResponses[keyof ChatAllResponses];

export type ChatCreateData = {
    /**
     * Request
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/chats';
};

export type ChatCreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatCreateError = ChatCreateErrors[keyof ChatCreateErrors];

export type ChatCreateResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChatByIdData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: number;
    };
    query?: never;
    url: '/chats/{chat_id}';
};

export type ChatByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatByIdError = ChatByIdErrors[keyof ChatByIdErrors];

export type ChatByIdResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChatExtendData = {
    /**
     * Request
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Chat Id
         */
        chat_id: number;
    };
    query?: never;
    url: '/chats/{chat_id}';
};

export type ChatExtendErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatExtendError = ChatExtendErrors[keyof ChatExtendErrors];

export type ChatExtendResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};