// This file is auto-generated by @hey-api/openapi-ts

/**
 * UserSchema
 */
export type UserSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Google Id
     */
    google_id: string;
    /**
     * Picture
     */
    picture?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

export type AuthLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/callback';
};

export type AuthCallbackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthLogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthGetMeResponses = {
    /**
     * Successful Response
     */
    200: UserSchema;
};

export type AuthGetMeResponse = AuthGetMeResponses[keyof AuthGetMeResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};